name: Publish Docker images

on:
  push:
    branches: [ main ]
    tags: [ 'v*.*.*' ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Define tags
        id: vars
        run: |
          OWNER=${{ secrets.DOCKERHUB_USERNAME }}
          SHA_TAG=${GITHUB_SHA::12}
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            REF_TAG=${GITHUB_REF#refs/tags/}
          else
            REF_TAG=latest
          fi
          echo "server_image=${OWNER}/rms-server" >> $GITHUB_OUTPUT
          echo "client_image=${OWNER}/rms-client" >> $GITHUB_OUTPUT
          echo "sha_tag=${SHA_TAG}" >> $GITHUB_OUTPUT
          echo "ref_tag=${REF_TAG}" >> $GITHUB_OUTPUT

      - name: Build and push server
        uses: docker/build-push-action@v6
        with:
          context: ./server
          file: ./server/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ${{ steps.vars.outputs.server_image }}:${{ steps.vars.outputs.sha_tag }}
            ${{ steps.vars.outputs.server_image }}:${{ steps.vars.outputs.ref_tag }}

      - name: Build and push client
        uses: docker/build-push-action@v6
        with:
          context: ./client
          file: ./client/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ${{ steps.vars.outputs.client_image }}:${{ steps.vars.outputs.sha_tag }}
            ${{ steps.vars.outputs.client_image }}:${{ steps.vars.outputs.ref_tag }}


